"""empty message

Revision ID: 37b59d754a1c
Revises: 4dd26881380d
Create Date: 2018-12-13 15:37:14.025051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b59d754a1c'
down_revision = '4dd26881380d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.String(length=50), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('hs_id', sa.Integer(), nullable=False),
    sa.Column('ss_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=100), nullable=True),
    sa.Column('total', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('out_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.cid'], ),
    sa.ForeignKeyConstraint(['hs_id'], ['hall_scheduling.hsid'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.sid'], ),
    sa.ForeignKeyConstraint(['ss_id'], ['seat_scheduling.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_no'), 'order', ['no'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_no'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
