"""empty message

Revision ID: 4eefb01ed3f2
Revises: 37b59d754a1c
Create Date: 2018-12-13 16:45:59.958505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eefb01ed3f2'
down_revision = '37b59d754a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'cinema_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order', 'hs_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order', 'movie_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order', 'seat_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order', 'ss_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'ss_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order', 'seat_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order', 'movie_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order', 'hs_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order', 'cinema_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
