"""empty message

Revision ID: c13babe71dfd
Revises: 4f07d8003003
Create Date: 2019-01-24 10:40:22.567312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13babe71dfd'
down_revision = '4f07d8003003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('good_id', sa.String(length=32), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('good_name', sa.String(length=255), nullable=False),
    sa.Column('show_img', sa.String(length=255), nullable=True),
    sa.Column('good_desc', sa.String(length=255), nullable=True),
    sa.Column('good_price', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('good_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
