"""empty message

Revision ID: d3a6f100ed40
Revises: be3ae799118d
Create Date: 2018-12-12 14:42:35.821250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a6f100ed40'
down_revision = 'be3ae799118d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall_scheduling',
    sa.Column('hsid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('origin_price', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.Column('hall_id', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.cid'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.hid'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('hsid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall_scheduling')
    # ### end Alembic commands ###
